import { Github, Linkedin, Save } from "lucide-react";

const ProfileEditForm = ({ form, setForm, saving, loading, saveProfile, setEditing, user }) => (
<form onSubmit={saveProfile} className="mt-5 space-y-4 border-t border-[var(--theme-border)] pt-5">
                            <h4 className="text-sm font-semibold">Edit your details</h4>
                            <label className="block text-sm font-medium text-[var(--theme-text-secondary)]">College or university<input name="college" value={form.college} onChange={(event) => setForm((current) => ({ ...current, college: event.target.value }))} maxLength={100} disabled={saving || loading} placeholder="Your college or university" className="mt-2 w-full rounded-lg border border-[var(--theme-border)] bg-[var(--theme-page)] px-3 py-2.5 text-sm text-[var(--theme-text)] outline-none focus:border-[var(--theme-accent)]" /></label>
                            <label className="block text-sm font-medium text-[var(--theme-text-secondary)]">Introduction<textarea name="bio" value={form.bio} onChange={(event) => setForm((current) => ({ ...current, bio: event.target.value }))} maxLength={300} rows={4} disabled={saving || loading} placeholder="What are you studying or working on?" className="mt-2 w-full resize-y rounded-lg border border-[var(--theme-border)] bg-[var(--theme-page)] px-3 py-2.5 text-sm leading-relaxed text-[var(--theme-text)] outline-none focus:border-[var(--theme-accent)]" /><span className="mt-1 block text-right text-xs text-[var(--theme-text-muted)]">{form.bio.length}/300</span></label>
                            <label className="block text-sm font-medium text-[var(--theme-text-secondary)]">Skills<input value={form.skills} onChange={(event) => setForm((current) => ({ ...current, skills: event.target.value }))} maxLength={500} disabled={saving || loading} placeholder="C++, React, Python, Problem solving" className="mt-2 w-full rounded-lg border border-[var(--theme-border)] bg-[var(--theme-page)] px-3 py-2.5 text-sm text-[var(--theme-text)] outline-none focus:border-[var(--theme-accent)]" /><span className="mt-1 block text-xs font-normal text-[var(--theme-text-muted)]">Separate skills with commas (up to 20).</span></label>
                            <div className="rounded-lg border border-[var(--theme-border)] p-4">
                                <h5 className="text-sm font-semibold">Current studies <span className="font-normal text-[var(--theme-text-muted)]">(optional)</span></h5>
                                <div className="mt-3 grid gap-3 sm:grid-cols-2">
                                    <label className="text-xs font-medium text-[var(--theme-text-secondary)]">Department<input value={form.department} onChange={(event) => setForm((current) => ({ ...current, department: event.target.value }))} maxLength={100} disabled={saving || loading} placeholder="e.g. Computer Science and Engineering" className="mt-1.5 w-full rounded-lg border border-[var(--theme-border)] bg-[var(--theme-page)] px-3 py-2.5 text-sm outline-none focus:border-[var(--theme-accent)]" /></label>
                                    <label className="text-xs font-medium text-[var(--theme-text-secondary)]">Current semester<input value={form.currentSemester} onChange={(event) => setForm((current) => ({ ...current, currentSemester: event.target.value }))} maxLength={40} disabled={saving || loading} placeholder="e.g. Semester 4" className="mt-1.5 w-full rounded-lg border border-[var(--theme-border)] bg-[var(--theme-page)] px-3 py-2.5 text-sm outline-none focus:border-[var(--theme-accent)]" /></label>
                                </div>
                            </div>
                            <div className="grid gap-3 sm:grid-cols-2">
                                <label className="text-sm font-medium text-[var(--theme-text-secondary)]"><span className="inline-flex items-center gap-1.5"><Github size={14} />GitHub profile</span><input type="url" value={form.github} onChange={(event) => setForm((current) => ({ ...current, github: event.target.value }))} maxLength={200} disabled={saving || loading} placeholder="https://github.com/username" className="mt-2 w-full rounded-lg border border-[var(--theme-border)] bg-[var(--theme-page)] px-3 py-2.5 text-sm outline-none focus:border-[var(--theme-accent)]" /></label>
                                <label className="text-sm font-medium text-[var(--theme-text-secondary)]"><span className="inline-flex items-center gap-1.5"><Linkedin size={14} />LinkedIn profile</span><input type="url" value={form.linkedin} onChange={(event) => setForm((current) => ({ ...current, linkedin: event.target.value }))} maxLength={200} disabled={saving || loading} placeholder="https://www.linkedin.com/in/username" className="mt-2 w-full rounded-lg border border-[var(--theme-border)] bg-[var(--theme-page)] px-3 py-2.5 text-sm outline-none focus:border-[var(--theme-accent)]" /></label>
                            </div>
                            <div className="flex justify-end gap-2"><button type="button" onClick={() => { setEditing(false); setForm(profileToForm(user?.profile)); }} className="rounded-full px-4 py-2 text-sm text-[var(--theme-text-secondary)] hover:bg-[var(--theme-surface-raised)]">Cancel</button><button type="submit" disabled={saving || loading} className="inline-flex items-center gap-2 rounded-full bg-[var(--theme-accent)] px-4 py-2 text-sm font-semibold text-[#06120D] disabled:opacity-50"><Save size={14} />{saving ? "Saving…" : "Save"}</button></div>
                        </form>
);

export default ProfileEditForm;
